### PR TITLE
bump agentkeepalive pkg version closes #69

### LINKED ISSUE #69: Protocol "https:" not supported.
I got this error. However the doc is telling the opposite.

### PR DESCRIPTION
**Pull request by AdrienFromToulouse**
If installed globally it will fail since the agentkeepalive pkg version on NPM is not the latest one.

### CODE REVIEW

**Comment by alexfernandez** [comment]
Please respect the original spacing with tabs, just change the line with the version for agentkeepalive. Thanks!

**Comment by AdrienFromToulouse** [comment]
sorry but npm --save will write with space. this is teh usual convention... the one should avoid to write manually a package.json...

**Comment by alexfernandez** [comment]
That is fine, but in the case of an existing `package.json` I would prefer
if you would respect the spacing. It improves the traceability.

**Comment by alexfernandez** [comment]
I will reimplement this if you don't mind.

**Pull request closed without merging**
